export const ADD_TODO = 'ADD_TODO';
export const CHECKBOX_UPDATE = 'CHECKBOX_UPDATE';
export const DELETE_ALL = 'DELETE_ALL';
export const DELETE_SINGLE_ITEM = 'DELETE_SINGLE_ITEM';
export const EDIT_SINGLE_ITEM = 'EDIT_SINGLE_ITEM';
